language: python
python:
- 3.8.5
cache: pip
before_install:
- sudo snap install nats-server
install:
- pip install -r requirements.txt
- pip install -e .
script: pytest
deploy:
  provider: pypi
  username: "__token__"
  on:
    branch: master
  password:
    secure: R3LwEAg6jrrDxsYUVuOI5VgkoZ34kbY3kxeviYRW35zcpu3A5FIiRbvmDZSuAWKYgmnffBGCY1Jvwq2Lysu/4eOFU0sUV+UButEZr86yRg7hllJ1B+N+5m3dXyeXRDKS7MvyghKR6VkoqEFlpO0VjZ4sID2UVFlMhVmKTQp/shA5PAaK3hFlxnt0U3M3RRQ7FAE1XGdKTWb1w7ze1rHjqeu443/vHPujJfxAtGbOUy8phCIyShmLyDclGZ8tCMg8tfQ0slE9gDnxdG7S0V+KTqUnenbuthTuv+cqp0qBgPI91+nLD6UxF42I4yIAQfwnlbIxjXP9eHKPaN464UOVxTaeNp5KAWa47tzM/HY+t7YmG/0V2jYjiuzYd7ollpY81+G3R2BGRCTR1waPebleUeH43H+TlgquODxRO+60bC459mEXWwr8uzOeYzgV1JlLv9p4cYY1DIf8nPTEXdRO3o6JEC35/ciTNVgy6G1pQU0G5Xi5fmHYkpcjhidaLSp+INZusvlmqp3k7joEp4uDngm498UxwpHb5RFGaB9bxLFs4QhkiqUXKRdQ37f8pQ+bizFf5/3zDLQEY7F2c71fHxEzi2RXxD7SpiVkTymCAgDs5gA2PuTZwExrBXjtyhf14UMSP9JFDxvnLWwqYtte9XhDAjWPWtGZlMeHAM/AlJE=
